### ISSUE TITLE
Heroku deployment with alternate link

### ISSUE THREAD

**Issue by GamerGoat112** [IDontCodee/Incognito#9]
When linking a freenom domain to my heroku app the domain works other than when I try to do anything using the proxy on the domain. When I do this it says that I'm on a private browser. This doesn't happen when I'm using the normal heroku app website though. I'm using unproxied cloudflare to set up dns. How would I fix this?

**Comment by mdoryammilwalrus** [comment]
I recommend you join discord for support:

**Comment by mdoryammilwalrus** [comment]
I recommend you join discord for support:

<a href="https://discord.gg/J3VPy5Vy8x" title="Join us on Discord">
<img src="https://invidget.switchblade.xyz/J3VPy5Vy8x?theme=light"></a>
